### Numpy -> Plays with arrays (numbers)
### Pandas -> datasets
### Matplotlib -> Data Visualization
### Seaborn ->  Data Visualization
### Scipy -> Statistical
### Sklearn -> Algorithm

# Numpy: Packages for Multidimensional Array

In [2]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arrange(5,20)

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(1,999)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [13]:
np.arange(29)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [14]:
np.arange(1,70,10)

array([ 1, 11, 21, 31, 41, 51, 61])

In [16]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(0,10,5,int)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.eye(22,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,

In [27]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [33]:
arr= np.random.randn(2,4)
arr

array([[ 0.56753846, -0.02149875,  0.24802125, -0.0897159 ],
       [ 0.36020416,  0.38383105,  1.80394399,  0.98399745]])

In [34]:
arr= np.random.randn(2,4)
arr

array([[-1.22097186, -0.28837312,  1.36348943, -0.33487133],
       [-1.01159212,  1.00650358,  1.53350124, -0.99263729]])

In [35]:
arr= np.random.randint(2,4)
arr

2

In [36]:
arr= np.random.randint(2,4)
arr

2

In [37]:
arr= np.random.randint(2,4)
arr

3

In [38]:
arr= np.random.randint(2,4)
arr

2

In [39]:
arr= np.random.randint(20,56,100)
arr

array([36, 25, 49, 50, 48, 31, 44, 46, 26, 30, 39, 33, 35, 47, 28, 51, 45,
       34, 51, 24, 53, 27, 34, 42, 20, 33, 27, 33, 48, 53, 53, 29, 49, 43,
       51, 32, 24, 43, 42, 26, 48, 20, 29, 49, 48, 51, 31, 51, 41, 39, 42,
       55, 23, 52, 26, 39, 24, 21, 32, 54, 43, 28, 31, 55, 37, 46, 47, 53,
       54, 41, 53, 53, 43, 39, 29, 48, 39, 44, 48, 41, 50, 46, 39, 31, 37,
       24, 31, 50, 28, 50, 46, 55, 51, 30, 49, 22, 50, 24, 35, 43])

In [40]:
arr= np.random.randint(2,100)
arr

7

In [41]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
rand_array =np.random.randint(0,10,50)
rand_array

array([9, 1, 5, 4, 0, 4, 5, 2, 7, 0, 6, 8, 2, 8, 8, 4, 7, 8, 2, 6, 6, 7,
       9, 8, 1, 3, 8, 0, 9, 9, 1, 5, 4, 4, 0, 1, 4, 6, 2, 1, 8, 6, 4, 4,
       2, 7, 8, 5, 8, 8])

In [43]:
sample_array.reshape(5,6)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [1]:
sample_array= np.arange(30)
sample_array

NameError: name 'np' is not defined

ValueError: cannot reshape array of size 30 into shape (5,5)

In [2]:
import numpy as np

In [3]:
sample_array= np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
sample_array= np.arange(22,30)
sample_array

array([22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
sample_array= np.random.randint(0,10,30)
sample_array

array([6, 0, 3, 8, 3, 0, 5, 0, 9, 8, 0, 1, 1, 0, 3, 8, 0, 9, 5, 4, 8, 3,
       8, 0, 5, 0, 0, 0, 2, 0])

In [6]:
sample_array.reshape(5,6)

array([[6, 0, 3, 8, 3, 0],
       [5, 0, 9, 8, 0, 1],
       [1, 0, 3, 8, 0, 9],
       [5, 4, 8, 3, 8, 0],
       [5, 0, 0, 0, 2, 0]])

In [7]:
sample_array.max()

9

In [8]:
sample_array.min()

0

In [9]:
sample_array.argmax()

8

In [15]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
a= np.random.rand(2,3)
a

array([[0.57239311, 0.1835805 , 0.87926561],
       [0.20582483, 0.60972417, 0.80981142]])

In [18]:
a.T

array([[0.57239311, 0.20582483],
       [0.1835805 , 0.60972417],
       [0.87926561, 0.80981142]])

In [19]:
a.T

array([[0.57239311, 0.20582483],
       [0.1835805 , 0.60972417],
       [0.87926561, 0.80981142]])

In [22]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
sample_array[0]

10

In [24]:
sample_array[2:5]

array([12, 13, 14])

## Two Dimensional array

In [25]:
import numpy as np

In [26]:
sample_matrix = np.array([[50, 20, 1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [28]:
sample_matrix[1,2]

21

In [29]:
sample_matrix[:0]

array([], shape=(0, 4), dtype=int32)

In [30]:
sample_matrix[2,3]

7

In [31]:
sample_matrix[2]

array([56, 76, 24,  7])

In [32]:
sample_matrix[0,2]

1

In [34]:
sample_matrix[:,2]

array([ 1, 21, 24])

In [35]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [33, 23],
       [ 7, 76]])

## Selection Techniques

In [2]:
import numpy as np
sample_array=np.arange(1,20)

In [3]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [5]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [6]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [7]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [8]:
np.max(sample_array)

19

In [9]:
np.min(sample_array)

1

In [10]:
np.argmax(sample_array)

18

In [11]:
np.argmin(sample_array)

0

In [12]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [13]:
np.std(sample_array)

5.477225575051661

In [14]:
np.var(sample_array)

30.0

In [15]:
np.mean(sample_array)

10.0

In [17]:
array=np.random.randn(3,4)
array

array([[-0.5960401 ,  0.02768324,  0.03320125, -0.29584961],
       [-0.58680634,  1.90417803,  0.38472864, -0.66213954],
       [-1.33063472,  0.20324611,  0.63357163, -0.19045413]])

In [18]:
np.round(array,decimals=2)

array([[-0.6 ,  0.03,  0.03, -0.3 ],
       [-0.59,  1.9 ,  0.38, -0.66],
       [-1.33,  0.2 ,  0.63, -0.19]])

In [19]:
sports=np.array(['golf','cricket','football','cricket'])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')